use_frameworks!

target 'NAXTMobileDataEntityFramework_Example' do
  pod 'NAXTMobileDataEntityFramework', :path => '../'

  target 'NAXTMobileDataEntityFramework_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
