use_frameworks!
platform :ios, '10.0'

target 'NMDEF.Base_Example' do
  pod 'NMDEF.Base', :path => '../'

  target 'NMDEF.Base_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.3.0'
    pod 'Nimble', '~> 7.3.0'
    pod 'FBSnapshotTestCase' , '~> 2.1.0'
    pod 'Nimble-Snapshots' , '~> 6.9.0'
  end
end
